### ISSUE TITLE
help locating data file

### ISSUE THREAD

**Issue by sourcesync** [eu-cdse/utilities#5]
Hi,

Thank you for this repo.

I'm trying to download the following the following file "S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE" from the Copernicus data hub, for further processing and research.

Do you know how to locate specific Sentinal-1A files?

Thanks.

**Comment by KanerLev** [comment]
Dear @sourcesync,

Sure. You can download "S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE" from 
-the [Copernicus Browser](https://browser.dataspace.copernicus.eu/), 
-[OData](https://documentation.dataspace.copernicus.eu/APIs/OData.html), 
-[S3 Access](https://documentation.dataspace.copernicus.eu/APIs/S3.html)

See [CDSE website](https://dataspace.copernicus.eu/) and [CDSE documentation](https://documentation.dataspace.copernicus.eu/Home.html) for above options and more (e.g. [Data Workspace](https://dataspace.copernicus.eu/analyse/data-workspace)).

If you haven't encountered already there is a [Community Forum](https://forum.dataspace.copernicus.eu/) in where CDSE Support Team provides feedback to the users with their inquiries. Moreover there is the CDSE Help desk you can reach out for cases such as bugs you encountered. For that you can [Submit a request](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new).

Kind regards

**Comment by sourcesync** [comment]
Thanks @KanerLev !

Yes I submitted a ticket to Copernicus and received the AWS S3 download instructions.

For anyone else having a similar issue, here is the command:

aws s3 sync s3://eodata/Sentinel-1/SAR/RAW/2022/07/10/S1A_S3_RAW__0SDH_20220710T213600_20220710T213625_044043_0541DB_56CE.SAFE/  <local_dir>

Thanks again!
